/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TimerRouteImport } from './routes/timer'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as RevisionRouteImport } from './routes/revision'
import { Route as ResourcesRouteImport } from './routes/resources'
import { Route as PracticeRouteImport } from './routes/practice'
import { Route as PlannerRouteImport } from './routes/planner'
import { Route as PhasesRouteImport } from './routes/phases'
import { Route as MistakesRouteImport } from './routes/mistakes'
import { Route as DsaRouteImport } from './routes/dsa'
import { Route as DoubtsRouteImport } from './routes/doubts'
import { Route as DataRouteImport } from './routes/data'
import { Route as CalendarRouteImport } from './routes/calendar'
import { Route as AnalyticsRouteImport } from './routes/analytics'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SubjectsIndexRouteImport } from './routes/subjects/index'
import { Route as SubjectsIdRouteImport } from './routes/subjects/$id'

const TimerRoute = TimerRouteImport.update({
  id: '/timer',
  path: '/timer',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const RevisionRoute = RevisionRouteImport.update({
  id: '/revision',
  path: '/revision',
  getParentRoute: () => rootRouteImport,
} as any)
const ResourcesRoute = ResourcesRouteImport.update({
  id: '/resources',
  path: '/resources',
  getParentRoute: () => rootRouteImport,
} as any)
const PracticeRoute = PracticeRouteImport.update({
  id: '/practice',
  path: '/practice',
  getParentRoute: () => rootRouteImport,
} as any)
const PlannerRoute = PlannerRouteImport.update({
  id: '/planner',
  path: '/planner',
  getParentRoute: () => rootRouteImport,
} as any)
const PhasesRoute = PhasesRouteImport.update({
  id: '/phases',
  path: '/phases',
  getParentRoute: () => rootRouteImport,
} as any)
const MistakesRoute = MistakesRouteImport.update({
  id: '/mistakes',
  path: '/mistakes',
  getParentRoute: () => rootRouteImport,
} as any)
const DsaRoute = DsaRouteImport.update({
  id: '/dsa',
  path: '/dsa',
  getParentRoute: () => rootRouteImport,
} as any)
const DoubtsRoute = DoubtsRouteImport.update({
  id: '/doubts',
  path: '/doubts',
  getParentRoute: () => rootRouteImport,
} as any)
const DataRoute = DataRouteImport.update({
  id: '/data',
  path: '/data',
  getParentRoute: () => rootRouteImport,
} as any)
const CalendarRoute = CalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticsRoute = AnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SubjectsIndexRoute = SubjectsIndexRouteImport.update({
  id: '/subjects/',
  path: '/subjects/',
  getParentRoute: () => rootRouteImport,
} as any)
const SubjectsIdRoute = SubjectsIdRouteImport.update({
  id: '/subjects/$id',
  path: '/subjects/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/calendar': typeof CalendarRoute
  '/data': typeof DataRoute
  '/doubts': typeof DoubtsRoute
  '/dsa': typeof DsaRoute
  '/mistakes': typeof MistakesRoute
  '/phases': typeof PhasesRoute
  '/planner': typeof PlannerRoute
  '/practice': typeof PracticeRoute
  '/resources': typeof ResourcesRoute
  '/revision': typeof RevisionRoute
  '/settings': typeof SettingsRoute
  '/timer': typeof TimerRoute
  '/subjects/$id': typeof SubjectsIdRoute
  '/subjects/': typeof SubjectsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/calendar': typeof CalendarRoute
  '/data': typeof DataRoute
  '/doubts': typeof DoubtsRoute
  '/dsa': typeof DsaRoute
  '/mistakes': typeof MistakesRoute
  '/phases': typeof PhasesRoute
  '/planner': typeof PlannerRoute
  '/practice': typeof PracticeRoute
  '/resources': typeof ResourcesRoute
  '/revision': typeof RevisionRoute
  '/settings': typeof SettingsRoute
  '/timer': typeof TimerRoute
  '/subjects/$id': typeof SubjectsIdRoute
  '/subjects': typeof SubjectsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/calendar': typeof CalendarRoute
  '/data': typeof DataRoute
  '/doubts': typeof DoubtsRoute
  '/dsa': typeof DsaRoute
  '/mistakes': typeof MistakesRoute
  '/phases': typeof PhasesRoute
  '/planner': typeof PlannerRoute
  '/practice': typeof PracticeRoute
  '/resources': typeof ResourcesRoute
  '/revision': typeof RevisionRoute
  '/settings': typeof SettingsRoute
  '/timer': typeof TimerRoute
  '/subjects/$id': typeof SubjectsIdRoute
  '/subjects/': typeof SubjectsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/analytics'
    | '/calendar'
    | '/data'
    | '/doubts'
    | '/dsa'
    | '/mistakes'
    | '/phases'
    | '/planner'
    | '/practice'
    | '/resources'
    | '/revision'
    | '/settings'
    | '/timer'
    | '/subjects/$id'
    | '/subjects/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/analytics'
    | '/calendar'
    | '/data'
    | '/doubts'
    | '/dsa'
    | '/mistakes'
    | '/phases'
    | '/planner'
    | '/practice'
    | '/resources'
    | '/revision'
    | '/settings'
    | '/timer'
    | '/subjects/$id'
    | '/subjects'
  id:
    | '__root__'
    | '/'
    | '/analytics'
    | '/calendar'
    | '/data'
    | '/doubts'
    | '/dsa'
    | '/mistakes'
    | '/phases'
    | '/planner'
    | '/practice'
    | '/resources'
    | '/revision'
    | '/settings'
    | '/timer'
    | '/subjects/$id'
    | '/subjects/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AnalyticsRoute: typeof AnalyticsRoute
  CalendarRoute: typeof CalendarRoute
  DataRoute: typeof DataRoute
  DoubtsRoute: typeof DoubtsRoute
  DsaRoute: typeof DsaRoute
  MistakesRoute: typeof MistakesRoute
  PhasesRoute: typeof PhasesRoute
  PlannerRoute: typeof PlannerRoute
  PracticeRoute: typeof PracticeRoute
  ResourcesRoute: typeof ResourcesRoute
  RevisionRoute: typeof RevisionRoute
  SettingsRoute: typeof SettingsRoute
  TimerRoute: typeof TimerRoute
  SubjectsIdRoute: typeof SubjectsIdRoute
  SubjectsIndexRoute: typeof SubjectsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/timer': {
      id: '/timer'
      path: '/timer'
      fullPath: '/timer'
      preLoaderRoute: typeof TimerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/revision': {
      id: '/revision'
      path: '/revision'
      fullPath: '/revision'
      preLoaderRoute: typeof RevisionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resources': {
      id: '/resources'
      path: '/resources'
      fullPath: '/resources'
      preLoaderRoute: typeof ResourcesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/practice': {
      id: '/practice'
      path: '/practice'
      fullPath: '/practice'
      preLoaderRoute: typeof PracticeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/planner': {
      id: '/planner'
      path: '/planner'
      fullPath: '/planner'
      preLoaderRoute: typeof PlannerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/phases': {
      id: '/phases'
      path: '/phases'
      fullPath: '/phases'
      preLoaderRoute: typeof PhasesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mistakes': {
      id: '/mistakes'
      path: '/mistakes'
      fullPath: '/mistakes'
      preLoaderRoute: typeof MistakesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dsa': {
      id: '/dsa'
      path: '/dsa'
      fullPath: '/dsa'
      preLoaderRoute: typeof DsaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/doubts': {
      id: '/doubts'
      path: '/doubts'
      fullPath: '/doubts'
      preLoaderRoute: typeof DoubtsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/data': {
      id: '/data'
      path: '/data'
      fullPath: '/data'
      preLoaderRoute: typeof DataRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calendar': {
      id: '/calendar'
      path: '/calendar'
      fullPath: '/calendar'
      preLoaderRoute: typeof CalendarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics': {
      id: '/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/subjects/': {
      id: '/subjects/'
      path: '/subjects'
      fullPath: '/subjects/'
      preLoaderRoute: typeof SubjectsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/subjects/$id': {
      id: '/subjects/$id'
      path: '/subjects/$id'
      fullPath: '/subjects/$id'
      preLoaderRoute: typeof SubjectsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AnalyticsRoute: AnalyticsRoute,
  CalendarRoute: CalendarRoute,
  DataRoute: DataRoute,
  DoubtsRoute: DoubtsRoute,
  DsaRoute: DsaRoute,
  MistakesRoute: MistakesRoute,
  PhasesRoute: PhasesRoute,
  PlannerRoute: PlannerRoute,
  PracticeRoute: PracticeRoute,
  ResourcesRoute: ResourcesRoute,
  RevisionRoute: RevisionRoute,
  SettingsRoute: SettingsRoute,
  TimerRoute: TimerRoute,
  SubjectsIdRoute: SubjectsIdRoute,
  SubjectsIndexRoute: SubjectsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
